[2023-06-01T18:12:47.329+0000] {processor.py:157} INFO - Started process (PID=24) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:12:47.330+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:12:47.330+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:12:47.330+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:12:47.333+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:12:47.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:12:47.333+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:12:47.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.030 seconds
[2023-06-01T18:13:17.473+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:17.474+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:13:17.474+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:13:17.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:17.476+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:13:17.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:13:17.476+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:17.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.016 seconds
[2023-06-01T18:13:47.599+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:47.600+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:13:47.600+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:13:47.600+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:47.602+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:13:47.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:13:47.602+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:13:47.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.024 seconds
[2023-06-01T18:14:17.721+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:17.738+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:14:17.739+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:14:17.738+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:17.740+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:14:17.740+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:14:17.741+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:17.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.044 seconds
[2023-06-01T18:14:56.063+0000] {processor.py:157} INFO - Started process (PID=24) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:56.064+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:14:56.064+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:14:56.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:56.066+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:14:56.065+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:14:56.066+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:14:56.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.029 seconds
[2023-06-01T18:15:26.184+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:26.208+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:15:26.209+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:15:26.208+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:26.211+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:15:26.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:15:26.211+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:26.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.049 seconds
[2023-06-01T18:15:56.291+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:56.310+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:15:56.310+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:15:56.310+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:56.313+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:15:56.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:15:56.313+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:15:56.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.044 seconds
[2023-06-01T18:16:26.291+0000] {processor.py:157} INFO - Started process (PID=24) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:26.291+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:16:26.292+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:16:26.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:26.293+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:16:26.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:16:26.294+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:26.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.026 seconds
[2023-06-01T18:16:56.410+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:56.418+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:16:56.418+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:16:56.418+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:56.420+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:16:56.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:16:56.420+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:16:56.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.033 seconds
[2023-06-01T18:17:26.550+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:26.567+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:17:26.568+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:17:26.568+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:26.570+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:17:26.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:17:26.570+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:26.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:17:56.696+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:56.713+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:17:56.714+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:17:56.714+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:56.716+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:17:56.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:17:56.716+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:17:56.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.035 seconds
[2023-06-01T18:18:26.824+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:26.842+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:18:26.842+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:18:26.842+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:26.844+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:18:26.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:18:26.844+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:26.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:18:56.976+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:56.993+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:18:56.994+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:18:56.993+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:56.995+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:18:56.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:18:56.996+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:18:57.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:19:27.130+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:27.147+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:19:27.147+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:19:27.147+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:27.149+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:19:27.149+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:19:27.150+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:27.171+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:19:57.281+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:57.299+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:19:57.299+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:19:57.299+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:57.301+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:19:57.300+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:19:57.301+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:19:57.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:20:27.432+0000] {processor.py:157} INFO - Started process (PID=97) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:27.450+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:20:27.451+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:20:27.451+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:27.453+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:20:27.452+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:20:27.453+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:27.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.044 seconds
[2023-06-01T18:20:57.579+0000] {processor.py:157} INFO - Started process (PID=106) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:57.597+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:20:57.598+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:20:57.598+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:57.600+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:20:57.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:20:57.600+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:20:57.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.043 seconds
[2023-06-01T18:21:27.740+0000] {processor.py:157} INFO - Started process (PID=115) to work on /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:21:27.757+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py for tasks to queue
[2023-06-01T18:21:27.758+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:21:27.758+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:21:27.760+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:21:27.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:21:27.760+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py
[2023-06-01T18:21:27.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/Csv2Delta_dag.py took 0.033 seconds
