[2023-06-09T20:34:08.042+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T20:34:06.531967+00:00 [queued]>
[2023-06-09T20:34:08.047+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T20:34:06.531967+00:00 [queued]>
[2023-06-09T20:34:08.047+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-09T20:34:08.054+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-09 20:34:06.531967+00:00
[2023-06-09T20:34:08.057+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2023-06-09T20:34:08.059+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wrapper_ex_dag', 'execute_function_task', 'manual__2023-06-09T20:34:06.531967+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/custom_dags/WrapperDag.py', '--cfg-path', '/tmp/tmp_n27_fb_']
[2023-06-09T20:34:08.061+0000] {standard_task_runner.py:85} INFO - Job 256: Subtask execute_function_task
[2023-06-09T20:34:08.086+0000] {task_command.py:410} INFO - Running <TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T20:34:06.531967+00:00 [running]> on host c712b1d8680f
[2023-06-09T20:34:08.133+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wrapper_ex_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T20:34:06.531967+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T20:34:06.531967+00:00'
[2023-06-09T20:34:08.134+0000] {CsvDagWrapper.py:22} INFO - CSV Delta Class Initialted
[2023-06-09T20:34:08.134+0000] {logging_mixin.py:149} INFO - Environment successfully parsed! Environment is Local
[2023-06-09T20:34:08.134+0000] {CsvDagWrapper.py:39} INFO - Environment successfully parsed! Environment is Local
[2023-06-09T20:34:08.134+0000] {logging_mixin.py:149} INFO - Table/s successfully parsed! Table:  ['CASE', 'CASE_PERS', 'PGM']
[2023-06-09T20:34:08.134+0000] {CsvDagWrapper.py:44} INFO - Table/s successfully parsed! Table:  ['CASE', 'CASE_PERS', 'PGM']
[2023-06-09T20:34:08.134+0000] {logging_mixin.py:149} INFO - Number of tables to be processed = 3
[2023-06-09T20:34:08.134+0000] {logging_mixin.py:149} INFO - TABLE_NAME IN ('CASE', 'CASE_PERS', 'PGM')
[2023-06-09T20:34:08.135+0000] {CsvDagWrapper.py:60} INFO - Works so far....
[2023-06-09T20:34:09.952+0000] {CsvDagWrapper.py:63} INFO - test
[2023-06-09T20:34:09.994+0000] {logging_mixin.py:149} INFO - This program loads CSV files into Local Delta Store!
[2023-06-09T20:34:10.000+0000] {logging_mixin.py:149} INFO - Task Ran successfully so far....
[2023-06-09T20:34:10.001+0000] {logging_mixin.py:149} INFO - ---------------------------------------------------------------------------------------------------------------------------------------
[2023-06-09T20:34:10.001+0000] {logging_mixin.py:149} INFO - Working on calsaws.CASE
[2023-06-09T20:34:10.001+0000] {logging_mixin.py:149} INFO - module 'Csv2Delta' has no attribute 'SeeIfTableExist'
[2023-06-09T20:34:10.014+0000] {logging_mixin.py:149} INFO - Good Bye!
[2023-06-09T20:34:10.014+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Python-Delta-Lake/custom_dags/WrapperDag.py", line 46, in execute_function_task
    task.RunCsvToDelta("Local",["CASE","CASE_PERS","PGM"],False)
  File "/opt/airflow/dags/Python-Delta-Lake/Csv2Delta/CsvDagWrapper.py", line 104, in RunCsvToDelta
    for row in sql_cursor_1:
pyodbc.ProgrammingError: Attempt to use a closed cursor.
[2023-06-09T20:34:10.021+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=wrapper_ex_dag, task_id=execute_function_task, execution_date=20230609T203406, start_date=20230609T203408, end_date=20230609T203410
[2023-06-09T20:34:10.029+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 256 for task execute_function_task (Attempt to use a closed cursor.; 61)
[2023-06-09T20:34:10.036+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T20:34:10.045+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
