[2023-06-29T23:37:55.334+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T23:37:54.532557+00:00 [queued]>
[2023-06-29T23:37:55.338+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T23:37:54.532557+00:00 [queued]>
[2023-06-29T23:37:55.338+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T23:37:55.344+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-29 23:37:54.532557+00:00
[2023-06-29T23:37:55.347+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-06-29T23:37:55.349+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore', 'execute_function_task', 'manual__2023-06-29T23:37:54.532557+00:00', '--job-id', '607', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmpjmrvm0re']
[2023-06-29T23:37:55.351+0000] {standard_task_runner.py:85} INFO - Job 607: Subtask execute_function_task
[2023-06-29T23:37:55.374+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T23:37:54.532557+00:00 [running]> on host a35364001907
[2023-06-29T23:37:55.416+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T23:37:54.532557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T23:37:54.532557+00:00'
[2023-06-29T23:37:55.416+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-06-29T23:37:55.416+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-06-29T23:37:55.416+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-06-29T23:37:57.615+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-06-29T23:37:57.616+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:50070')>.
[2023-06-29T23:37:57.617+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T23:37:57.629+0000] {logging_mixin.py:149} INFO - HDFS Connection Successfull
[2023-06-29T23:37:57.630+0000] {logging_mixin.py:149} INFO - HDFS Detected and Connected
[2023-06-29T23:37:57.630+0000] {logging_mixin.py:149} INFO - Spark Connection check - session found
[2023-06-29T23:37:58.087+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 2500 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-06-29T23:41:37.223+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-29T23:41:37.224+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 62. PIDs of all processes in the group: [63, 62]
[2023-06-29T23:41:37.225+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 62
[2023-06-29T23:41:37.225+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-29T23:41:37.225+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-29T23:41:37.225+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T23:41:37.226+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-06-29T23:41:37.226+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T23:41:37.228+0000] {SparkOracle2FileStore.py:177} INFO - Error Running Pipeline:An error occurred while calling o76.collectToPython
[2023-06-29T23:41:37.228+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-29T23:41:37.235+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=Oracle_to_Filestore, task_id=execute_function_task, execution_date=20230629T233754, start_date=20230629T233755, end_date=20230629T234137
[2023-06-29T23:41:37.638+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=63, status='terminated', started='23:37:55') (63) terminated with exit code None
[2023-06-29T23:41:37.639+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=62, status='terminated', exitcode=0, started='23:37:54') (62) terminated with exit code 0
