[2023-06-29T21:22:38.031+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T21:22:37.053124+00:00 [queued]>
[2023-06-29T21:22:38.035+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T21:22:37.053124+00:00 [queued]>
[2023-06-29T21:22:38.035+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T21:22:38.042+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-29 21:22:37.053124+00:00
[2023-06-29T21:22:38.045+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2023-06-29T21:22:38.048+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore', 'execute_function_task', 'manual__2023-06-29T21:22:37.053124+00:00', '--job-id', '586', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmpvmz3u4ly']
[2023-06-29T21:22:38.049+0000] {standard_task_runner.py:85} INFO - Job 586: Subtask execute_function_task
[2023-06-29T21:22:38.077+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T21:22:37.053124+00:00 [running]> on host a35364001907
[2023-06-29T21:22:38.121+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T21:22:37.053124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T21:22:37.053124+00:00'
[2023-06-29T21:22:38.122+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-06-29T21:22:38.122+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-06-29T21:22:38.122+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-06-29T21:22:41.838+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-06-29T21:22:41.839+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:50070')>.
[2023-06-29T21:22:41.840+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T21:22:41.846+0000] {logging_mixin.py:149} INFO - HDFS Connection Successfull
[2023-06-29T21:22:41.847+0000] {logging_mixin.py:149} INFO - HDFS Detected and Connected
[2023-06-29T21:22:41.847+0000] {logging_mixin.py:149} INFO - Spark Connection check - session found
[2023-06-29T21:22:42.374+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 4000 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-06-29T21:22:45.530+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.531+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.536+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.536+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.537+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.538+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.539+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-06-29T21:22:45.550+0000] {logging_mixin.py:149} INFO - ['PR_LRS.FOSTER_FAM_AGNC', 'PR_LRS.EBT_EXPG_EXCPT', 'PR_LRS.ENCL_ESTIMATE', 'PR_LRS.UNIT', 'PR_LRS.IEVS_SAVE_EXCEPT', 'PR_LRS.WTW_24_MONTH_SIGN_DATE', 'PR_LRS.RULES_ADMIN', 'PR_LRS.COUNTY_PARAMTR_ADMIN_HST', 'PR_LRS.C4Y_PREG', 'PR_LRS.IEVS_PRISON_MATCH', 'PR_LRS.ORG_ACCT', 'PR_LRS.TRAIN_PGM', 'PR_LRS.IFD_SSI', 'PR_LRS.C4Y_PERS_NON_COMPL', 'PR_LRS.POS', 'PR_LRS.ADH_SUMM', 'PR_LRS.WDTIP_PGM_PARTICPTN', 'PR_LRS.HEAR_SUMM', 'PR_LRS.WDTIP_ALERT', 'PR_LRS.IHSS_REFRL', 'PR_LRS.SFIS_COUNTY_INFO', 'PR_LRS.STAFF', 'PR_LRS.MEDS_ALERT_CONFIG', 'PR_LRS.BATCH_JOB', 'PR_LRS.IHSS_CASE', 'PR_LRS.RULES_ADMIN_HST', 'PR_LRS.TAX_INTRCPT', 'PR_LRS.WTW_24_MONTH_SIGN_DATE_HST', 'PR_LRS.COUNTY_PARAMTR_ADMIN', 'PR_LRS.OCAT', 'PR_LRS.WDTIP_EXCEED_CLOCK', 'PR_LRS.AUTO_ACTN', 'PR_LRS.IFD_DUPL_DETL', 'PR_LRS.EBT_FRAUD_ACTIV', 'PR_LRS.GA_GR_TIME_LIMIT', 'PR_LRS.GRP_HOMES', 'PR_LRS.ASSET_VERIF', 'PR_LRS.FUND_CODE_MAP', 'PR_LRS.C4Y_OTHER_PGM_ASSIST', 'PR_LRS.IEVS_FF_MEDS', 'PR_LRS.COLLAB_CONTRACT', 'PR_LRS.WDTIP_APPRCH_CLOCK', 'PR_LRS.EXTRNL_STAFF_COUNTY_STAT', 'PR_LRS.VEND_IDENTIF', 'PR_LRS.OCAT_PERS', 'PR_LRS.MEDS_ALERT_CONFIG_HST', 'PR_LRS.WPR_SAMPLE_CASE', 'PR_LRS.PERS_TIME_TRACK_DETL']
[2023-06-29T21:22:45.551+0000] {logging_mixin.py:149} INFO - processing 1 out of 48
[2023-06-29T21:22:45.552+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.FOSTER_FAM_AGNC
[2023-06-29T21:22:45.552+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:22:47.339+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.FOSTER_FAM_AGNC
[2023-06-29T21:22:47.339+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:22:48.601+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-06-29T21:22:49.275+0000] {logging_mixin.py:149} INFO - Filter Processor Disabled
[2023-06-29T21:22:49.275+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:22:51.734+0000] {logging_mixin.py:149} INFO - 34262
[2023-06-29T21:22:51.734+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:22:53.039+0000] {logging_mixin.py:149} INFO - Checking if HDFS Directory /dev/FOSTER_FAM_AGNC exists...
[2023-06-29T21:22:53.039+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T21:22:53.042+0000] {logging_mixin.py:149} INFO - HDFS Connection Successfull
[2023-06-29T21:22:53.042+0000] {client.py:320} INFO - Fetching status for '/dev/FOSTER_FAM_AGNC'.
[2023-06-29T21:22:53.045+0000] {logging_mixin.py:149} INFO - HDFS Path Exists
[2023-06-29T21:22:53.045+0000] {logging_mixin.py:149} INFO - Should go in here if table dir exists
[2023-06-29T21:22:54.780+0000] {logging_mixin.py:149} INFO - read dir table should not fail and go in here...
[2023-06-29T21:23:02.298+0000] {logging_mixin.py:149} INFO - no rows to upsert on table FOSTER_FAM_AGNC
[2023-06-29T21:23:05.489+0000] {logging_mixin.py:149} INFO - Updating rows on table FOSTER_FAM_AGNC
[2023-06-29T21:23:15.497+0000] {logging_mixin.py:149} INFO - no rows to delete on table FOSTER_FAM_AGNC
[2023-06-29T21:23:15.498+0000] {logging_mixin.py:149} INFO - Table Processing complete for PR_LRS.FOSTER_FAM_AGNC
[2023-06-29T21:23:15.498+0000] {logging_mixin.py:149} INFO - processing 2 out of 48
[2023-06-29T21:23:15.498+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.EBT_EXPG_EXCPT
[2023-06-29T21:23:15.498+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:23:16.782+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.EBT_EXPG_EXCPT
[2023-06-29T21:23:16.782+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:23:17.943+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-06-29T21:23:18.512+0000] {logging_mixin.py:149} INFO - Filter Processor Disabled
[2023-06-29T21:23:18.512+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:23:20.305+0000] {logging_mixin.py:149} INFO - 316506
[2023-06-29T21:23:20.305+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:23:21.684+0000] {logging_mixin.py:149} INFO - Checking if HDFS Directory /dev/EBT_EXPG_EXCPT exists...
[2023-06-29T21:23:21.685+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T21:23:21.689+0000] {logging_mixin.py:149} INFO - HDFS Connection Successfull
[2023-06-29T21:23:21.689+0000] {client.py:320} INFO - Fetching status for '/dev/EBT_EXPG_EXCPT'.
[2023-06-29T21:23:21.691+0000] {logging_mixin.py:149} INFO - HDFS Path Exists
[2023-06-29T21:23:21.691+0000] {logging_mixin.py:149} INFO - Should go in here if table dir exists
[2023-06-29T21:23:21.768+0000] {logging_mixin.py:149} INFO - read dir table should not fail and go in here...
[2023-06-29T21:23:57.655+0000] {logging_mixin.py:149} INFO - no rows to upsert on table EBT_EXPG_EXCPT
[2023-06-29T21:24:13.912+0000] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-06-29T21:24:13.913+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 54. PIDs of all processes in the group: [55, 54]
[2023-06-29T21:24:13.913+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 54
[2023-06-29T21:24:13.914+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-29T21:24:13.914+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-29T21:24:13.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:13.936+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-06-29T21:24:13.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:13.937+0000] {logging_mixin.py:149} INFO - Error Processing Table PR_LRS.EBT_EXPG_EXCPT:An error occurred while calling o193.isEmpty
[2023-06-29T21:24:13.937+0000] {logging_mixin.py:149} INFO - processing 2 out of 48
[2023-06-29T21:24:13.937+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.ENCL_ESTIMATE
[2023-06-29T21:24:13.937+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:24:14.427+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2023-06-29T21:24:14.427+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.427+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-06-29T21:24:14.427+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.427+0000] {logging_mixin.py:149} INFO - Error in reading oracle table by query: An error occurred while calling o202.load
[2023-06-29T21:24:14.427+0000] {logging_mixin.py:149} INFO - Could not get min count: 'NoneType' object has no attribute 'head'
[2023-06-29T21:24:14.427+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.ENCL_ESTIMATE
[2023-06-29T21:24:14.427+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Error in reading oracle table by query: [Errno 111] Connection refused
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Could not get max count: 'NoneType' object has no attribute 'head'
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - could not reliablily get upper and lower bounds of table PR_LRS.ENCL_ESTIMATE, reading without partition 
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Read on oracle table failed: [Errno 111] Connection refused
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Filter Processor Disabled
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Error in reading oracle table by rowcount: [Errno 111] Connection refused
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - None
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Error in reading oracle table by rowcount: [Errno 111] Connection refused
[2023-06-29T21:24:14.428+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.428+0000] {logging_mixin.py:149} INFO - Checking if HDFS Directory /dev/ENCL_ESTIMATE exists...
[2023-06-29T21:24:14.428+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T21:24:14.432+0000] {logging_mixin.py:149} INFO - HDFS Connection Successfull
[2023-06-29T21:24:14.432+0000] {client.py:320} INFO - Fetching status for '/dev/ENCL_ESTIMATE'.
[2023-06-29T21:24:14.434+0000] {logging_mixin.py:149} INFO - HDFS Path Exists
[2023-06-29T21:24:14.434+0000] {logging_mixin.py:149} INFO - Should go in here if table dir exists
[2023-06-29T21:24:14.435+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.435+0000] {logging_mixin.py:149} INFO - Error in reading dataframe:[Errno 111] Connection refused
[2023-06-29T21:24:14.435+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-06-29T21:24:14.435+0000] {logging_mixin.py:149} INFO - Error in writing dataframe:'NoneType' object has no attribute 'write'
[2023-06-29T21:24:14.435+0000] {logging_mixin.py:149} INFO - Table write error, skipping table
[2023-06-29T21:24:14.435+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-29T21:24:14.442+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=Oracle_to_Filestore, task_id=execute_function_task, execution_date=20230629T212237, start_date=20230629T212238, end_date=20230629T212414
[2023-06-29T21:24:14.461+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=55, status='terminated', started='21:22:37') (55) terminated with exit code None
[2023-06-29T21:24:14.461+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=54, status='terminated', exitcode=0, started='21:22:37') (54) terminated with exit code 0
