[2023-06-15T16:15:30.398+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task scheduled__2023-06-15T15:00:00+00:00 [queued]>
[2023-06-15T16:15:30.402+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task scheduled__2023-06-15T15:00:00+00:00 [queued]>
[2023-06-15T16:15:30.402+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T16:15:30.408+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-15 15:00:00+00:00
[2023-06-15T16:15:30.411+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2023-06-15T16:15:30.413+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wrapper_ex_dag', 'execute_function_task', 'scheduled__2023-06-15T15:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/custom_dags/WrapperDag.py', '--cfg-path', '/tmp/tmpwl142lzh']
[2023-06-15T16:15:30.414+0000] {standard_task_runner.py:85} INFO - Job 275: Subtask execute_function_task
[2023-06-15T16:15:30.438+0000] {task_command.py:410} INFO - Running <TaskInstance: wrapper_ex_dag.execute_function_task scheduled__2023-06-15T15:00:00+00:00 [running]> on host 6fb96d18f9da
[2023-06-15T16:15:30.481+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wrapper_ex_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-15T15:00:00+00:00'
[2023-06-15T16:15:30.481+0000] {CsvDagWrapper.py:22} INFO - CSV Delta Class Initialted
[2023-06-15T16:15:30.481+0000] {logging_mixin.py:149} INFO - Environment successfully parsed! Environment is Local
[2023-06-15T16:15:30.481+0000] {CsvDagWrapper.py:39} INFO - Environment successfully parsed! Environment is Local
[2023-06-15T16:15:30.481+0000] {logging_mixin.py:149} INFO - Table/s successfully parsed! Table:  ['CASE', 'PTR']
[2023-06-15T16:15:30.482+0000] {CsvDagWrapper.py:44} INFO - Table/s successfully parsed! Table:  ['CASE', 'PTR']
[2023-06-15T16:15:30.482+0000] {logging_mixin.py:149} INFO - Number of tables to be processed = 2
[2023-06-15T16:15:30.482+0000] {logging_mixin.py:149} INFO - TABLE_NAME IN ('CASE', 'PTR')
[2023-06-15T16:15:30.482+0000] {CsvDagWrapper.py:60} INFO - Works so far....
[2023-06-15T16:15:32.996+0000] {CsvDagWrapper.py:63} INFO - test
[2023-06-15T16:15:33.043+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Python-Delta-Lake/custom_dags/WrapperDag.py", line 46, in execute_function_task
    task.RunCsvToDelta("Local",["CASE","PTR"],False)
  File "/opt/airflow/dags/Python-Delta-Lake/Csv2Delta/CsvDagWrapper.py", line 71, in RunCsvToDelta
    sql_connection_1 = pyodbc.connect(sql_server_connection_string)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "DAU" requested by the login. The login failed. (4060) (SQLDriverConnect)')
[2023-06-15T16:15:33.048+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=wrapper_ex_dag, task_id=execute_function_task, execution_date=20230615T150000, start_date=20230615T161530, end_date=20230615T161533
[2023-06-15T16:15:33.058+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 275 for task execute_function_task (('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "DAU" requested by the login. The login failed. (4060) (SQLDriverConnect)'); 54)
[2023-06-15T16:15:33.071+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T16:15:33.081+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
