[2023-07-11T18:49:43.512+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore_Concurrent.execute_task2 manual__2023-07-11T18:49:42.706625+00:00 [queued]>
[2023-07-11T18:49:43.516+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore_Concurrent.execute_task2 manual__2023-07-11T18:49:42.706625+00:00 [queued]>
[2023-07-11T18:49:43.516+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T18:49:43.523+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_task2> on 2023-07-11 18:49:42.706625+00:00
[2023-07-11T18:49:43.526+0000] {standard_task_runner.py:57} INFO - Started process 7760 to run task
[2023-07-11T18:49:43.529+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore_Concurrent', 'execute_task2', 'manual__2023-07-11T18:49:42.706625+00:00', '--job-id', '1015', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmp9vgrzahg']
[2023-07-11T18:49:43.530+0000] {standard_task_runner.py:85} INFO - Job 1015: Subtask execute_task2
[2023-07-11T18:49:43.556+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore_Concurrent.execute_task2 manual__2023-07-11T18:49:42.706625+00:00 [running]> on host 876817aabcc6
[2023-07-11T18:49:43.599+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore_Concurrent' AIRFLOW_CTX_TASK_ID='execute_task2' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T18:49:42.706625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T18:49:42.706625+00:00'
[2023-07-11T18:49:43.600+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:49:43.600+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:49:43.600+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-07-11T18:49:43.600+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-07-11T18:49:45.965+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-07-11T18:49:45.965+0000] {logging_mixin.py:149} INFO - Spark Connection check - session found
[2023-07-11T18:49:46.479+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 2500 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-07-11T18:49:49.756+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.757+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.758+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.761+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.762+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.762+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.764+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.765+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.776+0000] {SparkOracle2FileStore.py:81} INFO - Skipping log tables and reading tables directly
[2023-07-11T18:49:49.777+0000] {SparkOracle2FileStore.py:91} INFO - processing 1 out of 22
[2023-07-11T18:49:49.777+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.TAX_INTRCPT
[2023-07-11T18:49:49.777+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:49:51.923+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.TAX_INTRCPT
[2023-07-11T18:49:51.923+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:49:53.137+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:49:53.718+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:49:53.719+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:49:55.004+0000] {SparkOracle2FileStore.py:114} INFO - 173371
[2023-07-11T18:49:55.004+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:49:56.640+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/TAX_INTRCPT
[2023-07-11T18:49:56.640+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:49:56.640+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:49:57.774+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:50:25.495+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table TAX_INTRCPT
[2023-07-11T18:50:46.952+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table TAX_INTRCPT
[2023-07-11T18:51:52.777+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table TAX_INTRCPT
[2023-07-11T18:51:52.778+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.TAX_INTRCPT
[2023-07-11T18:51:52.877+0000] {SparkOracle2FileStore.py:91} INFO - processing 2 out of 22
[2023-07-11T18:51:52.877+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column HST_ID on table PR_LRS.WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:51:52.877+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:51:54.133+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column HST_ID on table PR_LRS.WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:51:54.133+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:51:55.402+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:51:55.986+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:51:55.986+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:51:57.438+0000] {SparkOracle2FileStore.py:114} INFO - 347499
[2023-07-11T18:51:57.438+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:51:58.773+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:51:58.773+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:51:58.773+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:51:58.829+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:52:41.274+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:53:25.497+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:54:42.633+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:54:42.634+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.WTW_24_MONTH_SIGN_DATE_HST
[2023-07-11T18:54:42.718+0000] {SparkOracle2FileStore.py:91} INFO - processing 3 out of 22
[2023-07-11T18:54:42.718+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:42.718+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:44.107+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:44.107+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:46.356+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:54:46.908+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:54:46.908+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:48.031+0000] {SparkOracle2FileStore.py:114} INFO - 18240
[2023-07-11T18:54:48.032+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:49.144+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:49.144+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:54:49.144+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:54:49.194+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:54:52.851+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:54.418+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:59.113+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:59.114+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.COUNTY_PARAMTR_ADMIN
[2023-07-11T18:54:59.196+0000] {SparkOracle2FileStore.py:91} INFO - processing 4 out of 22
[2023-07-11T18:54:59.197+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.OCAT
[2023-07-11T18:54:59.197+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:55:00.385+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.OCAT
[2023-07-11T18:55:00.385+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:55:01.586+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:55:02.180+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:55:02.180+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:55:03.533+0000] {SparkOracle2FileStore.py:114} INFO - 176399
[2023-07-11T18:55:03.534+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:55:04.892+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/OCAT
[2023-07-11T18:55:04.892+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:55:04.892+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:55:04.942+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:55:42.976+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table OCAT
[2023-07-11T18:56:17.116+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table OCAT
[2023-07-11T18:57:25.571+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table OCAT
[2023-07-11T18:57:25.571+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.OCAT
[2023-07-11T18:57:25.639+0000] {SparkOracle2FileStore.py:190} INFO - Tables Thresholds reached, restarting spark context
[2023-07-11T18:57:25.639+0000] {logging_mixin.py:149} INFO - Stopping Spark Context
[2023-07-11T18:57:25.900+0000] {logging_mixin.py:149} INFO - Restarting Spark Context
[2023-07-11T18:57:25.900+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:57:25.900+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-07-11T18:57:25.900+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-07-11T18:57:25.985+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-07-11T18:57:25.985+0000] {SparkOracle2FileStore.py:91} INFO - processing 5 out of 22
[2023-07-11T18:57:25.985+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:25.986+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:28.916+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:28.916+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:30.080+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:57:30.606+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:57:30.606+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:31.722+0000] {SparkOracle2FileStore.py:114} INFO - 17802
[2023-07-11T18:57:31.722+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:33.152+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:33.152+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:57:33.152+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:57:33.656+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:57:39.511+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:41.719+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:49.557+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:49.557+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.WDTIP_EXCEED_CLOCK
[2023-07-11T18:57:49.631+0000] {SparkOracle2FileStore.py:91} INFO - processing 6 out of 22
[2023-07-11T18:57:49.632+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.AUTO_ACTN
[2023-07-11T18:57:49.632+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:51.202+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.AUTO_ACTN
[2023-07-11T18:57:51.202+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:53.072+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:57:53.855+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:57:53.856+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:55.330+0000] {SparkOracle2FileStore.py:114} INFO - 13113
[2023-07-11T18:57:55.330+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:57.022+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/AUTO_ACTN
[2023-07-11T18:57:57.023+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:57:57.023+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:57:57.067+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:57:59.219+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table AUTO_ACTN
[2023-07-11T18:58:00.610+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table AUTO_ACTN
[2023-07-11T18:58:04.996+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table AUTO_ACTN
[2023-07-11T18:58:04.997+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.AUTO_ACTN
[2023-07-11T18:58:05.061+0000] {SparkOracle2FileStore.py:91} INFO - processing 7 out of 22
[2023-07-11T18:58:05.061+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.IFD_DUPL_DETL
[2023-07-11T18:58:05.061+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:58:06.323+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.IFD_DUPL_DETL
[2023-07-11T18:58:06.324+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:58:07.462+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:58:08.163+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:58:08.163+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:58:09.458+0000] {SparkOracle2FileStore.py:114} INFO - 353610
[2023-07-11T18:58:09.459+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:58:10.766+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/IFD_DUPL_DETL
[2023-07-11T18:58:10.767+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:58:10.767+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:58:10.824+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:58:50.162+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table IFD_DUPL_DETL
[2023-07-11T18:59:21.902+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table IFD_DUPL_DETL
[2023-07-11T19:00:58.590+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table IFD_DUPL_DETL
[2023-07-11T19:00:58.592+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.IFD_DUPL_DETL
[2023-07-11T19:00:58.670+0000] {SparkOracle2FileStore.py:91} INFO - processing 8 out of 22
[2023-07-11T19:00:58.670+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.EBT_FRAUD_ACTIV
[2023-07-11T19:00:58.670+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:00:59.913+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.EBT_FRAUD_ACTIV
[2023-07-11T19:00:59.913+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:01.011+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:01:01.609+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:01:01.609+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:03.026+0000] {SparkOracle2FileStore.py:114} INFO - 21414
[2023-07-11T19:01:03.026+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:04.280+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/EBT_FRAUD_ACTIV
[2023-07-11T19:01:04.280+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:01:04.280+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:01:04.331+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:01:07.278+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table EBT_FRAUD_ACTIV
[2023-07-11T19:01:10.535+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table EBT_FRAUD_ACTIV
[2023-07-11T19:01:16.384+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table EBT_FRAUD_ACTIV
[2023-07-11T19:01:16.384+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.EBT_FRAUD_ACTIV
[2023-07-11T19:01:16.462+0000] {SparkOracle2FileStore.py:91} INFO - processing 9 out of 22
[2023-07-11T19:01:16.462+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.GA_GR_TIME_LIMIT
[2023-07-11T19:01:16.462+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:17.598+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.GA_GR_TIME_LIMIT
[2023-07-11T19:01:17.598+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:18.731+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:01:19.398+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:01:19.398+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:20.662+0000] {SparkOracle2FileStore.py:114} INFO - 556545
[2023-07-11T19:01:20.662+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:21.913+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/GA_GR_TIME_LIMIT
[2023-07-11T19:01:21.913+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:01:21.913+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:01:21.957+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:01:43.302+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table GA_GR_TIME_LIMIT
[2023-07-11T19:02:08.564+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table GA_GR_TIME_LIMIT
[2023-07-11T19:02:53.669+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table GA_GR_TIME_LIMIT
[2023-07-11T19:02:53.670+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.GA_GR_TIME_LIMIT
[2023-07-11T19:02:53.742+0000] {SparkOracle2FileStore.py:190} INFO - Tables Thresholds reached, restarting spark context
[2023-07-11T19:02:53.742+0000] {logging_mixin.py:149} INFO - Stopping Spark Context
[2023-07-11T19:02:53.882+0000] {logging_mixin.py:149} INFO - Restarting Spark Context
[2023-07-11T19:02:53.882+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T19:02:53.882+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-07-11T19:02:53.883+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-07-11T19:02:53.972+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-07-11T19:02:53.972+0000] {SparkOracle2FileStore.py:91} INFO - processing 10 out of 22
[2023-07-11T19:02:53.972+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.GRP_HOMES
[2023-07-11T19:02:53.972+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:02:57.575+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.GRP_HOMES
[2023-07-11T19:02:57.576+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:02:58.744+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:02:59.261+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:02:59.262+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:03:00.524+0000] {SparkOracle2FileStore.py:114} INFO - 35184
[2023-07-11T19:03:00.524+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:03:01.669+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/GRP_HOMES
[2023-07-11T19:03:01.670+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:03:01.670+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:03:02.019+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:03:15.182+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table GRP_HOMES
[2023-07-11T19:03:25.673+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table GRP_HOMES
[2023-07-11T19:03:48.412+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table GRP_HOMES
[2023-07-11T19:03:48.413+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.GRP_HOMES
[2023-07-11T19:03:48.477+0000] {SparkOracle2FileStore.py:91} INFO - processing 11 out of 22
[2023-07-11T19:03:48.477+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.ASSET_VERIF
[2023-07-11T19:03:48.478+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:03:49.714+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.ASSET_VERIF
[2023-07-11T19:03:49.714+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:03:50.899+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:03:51.476+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:03:51.477+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:03:53.167+0000] {SparkOracle2FileStore.py:114} INFO - 1628991
[2023-07-11T19:03:53.167+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:03:55.231+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/ASSET_VERIF
[2023-07-11T19:03:55.231+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:03:55.231+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:03:55.281+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:05:36.418+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table ASSET_VERIF
[2023-07-11T19:07:15.834+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table ASSET_VERIF
[2023-07-11T19:10:19.024+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 212, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 243, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 811, in refresh_from_db
    ti = qry.one_or_none()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:24.735+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:36.599+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:42.014+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:47.241+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:52.281+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
