[2023-06-01T18:07:10.432+0000] {processor.py:157} INFO - Started process (PID=23) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:10.432+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:07:10.433+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:07:10.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:10.435+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:07:10.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:07:10.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:10.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.018 seconds
[2023-06-01T18:07:40.553+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:40.554+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:07:40.554+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:07:40.554+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:40.555+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:07:40.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:07:40.556+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:07:40.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.030 seconds
[2023-06-01T18:08:10.691+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:10.691+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:08:10.692+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:08:10.692+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:10.693+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:08:10.693+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:08:10.694+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:10.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.017 seconds
[2023-06-01T18:08:40.813+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:40.815+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:08:40.816+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:08:40.816+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:40.818+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:08:40.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:08:40.818+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:08:40.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.040 seconds
[2023-06-01T18:09:10.962+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:10.965+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:09:10.965+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:09:10.965+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:10.967+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:09:10.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:09:10.967+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:11.011+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.051 seconds
[2023-06-01T18:09:40.115+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:40.116+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:09:40.117+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:09:40.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:40.119+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:09:40.118+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:09:40.119+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:09:40.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.024 seconds
[2023-06-01T18:10:05.028+0000] {processor.py:157} INFO - Started process (PID=23) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:05.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:10:05.029+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:10:05.029+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:05.031+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:10:05.030+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:10:05.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:05.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.054 seconds
[2023-06-01T18:10:35.131+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:35.132+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:10:35.132+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:10:35.132+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:35.134+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:10:35.134+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:10:35.134+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:10:35.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.045 seconds
[2023-06-01T18:11:05.282+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:05.283+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:11:05.283+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:11:05.283+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:05.285+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:11:05.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:11:05.285+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:05.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.045 seconds
[2023-06-01T18:11:35.430+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:35.431+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:11:35.431+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:11:35.431+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:35.433+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:11:35.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:11:35.433+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:11:35.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.044 seconds
[2023-06-01T18:12:05.576+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:12:05.577+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py for tasks to queue
[2023-06-01T18:12:05.577+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:12:05.577+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:12:05.579+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:12:05.578+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/dags/WrapperDag.py", line 8, in <module>
    from utils.CsvDagWrapper import RunCsvToDelta
ModuleNotFoundError: No module named 'utils'
[2023-06-01T18:12:05.579+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py
[2023-06-01T18:12:05.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/dags/WrapperDag.py took 0.046 seconds
