[2023-07-11T18:49:43.510+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore_Concurrent.execute_task1 manual__2023-07-11T18:49:42.706625+00:00 [queued]>
[2023-07-11T18:49:43.514+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore_Concurrent.execute_task1 manual__2023-07-11T18:49:42.706625+00:00 [queued]>
[2023-07-11T18:49:43.514+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T18:49:43.520+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_task1> on 2023-07-11 18:49:42.706625+00:00
[2023-07-11T18:49:43.524+0000] {standard_task_runner.py:57} INFO - Started process 7759 to run task
[2023-07-11T18:49:43.526+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore_Concurrent', 'execute_task1', 'manual__2023-07-11T18:49:42.706625+00:00', '--job-id', '1014', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmpo5jr02hk']
[2023-07-11T18:49:43.528+0000] {standard_task_runner.py:85} INFO - Job 1014: Subtask execute_task1
[2023-07-11T18:49:43.554+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore_Concurrent.execute_task1 manual__2023-07-11T18:49:42.706625+00:00 [running]> on host 876817aabcc6
[2023-07-11T18:49:43.596+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore_Concurrent' AIRFLOW_CTX_TASK_ID='execute_task1' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T18:49:42.706625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T18:49:42.706625+00:00'
[2023-07-11T18:49:43.597+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:49:43.597+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:49:43.597+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-07-11T18:49:43.597+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-07-11T18:49:45.999+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-07-11T18:49:45.999+0000] {logging_mixin.py:149} INFO - Spark Connection check - session found
[2023-07-11T18:49:46.488+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 2500 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-07-11T18:49:49.784+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.785+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.786+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.790+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.790+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.790+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.792+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.793+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:248: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

[2023-07-11T18:49:49.804+0000] {SparkOracle2FileStore.py:81} INFO - Skipping log tables and reading tables directly
[2023-07-11T18:49:49.805+0000] {SparkOracle2FileStore.py:91} INFO - processing 1 out of 26
[2023-07-11T18:49:49.805+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.FOSTER_FAM_AGNC
[2023-07-11T18:49:49.805+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:49:51.636+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.FOSTER_FAM_AGNC
[2023-07-11T18:49:51.636+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:49:52.906+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:49:53.475+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:49:53.476+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:49:54.834+0000] {SparkOracle2FileStore.py:114} INFO - 34262
[2023-07-11T18:49:54.834+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:49:57.250+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/FOSTER_FAM_AGNC
[2023-07-11T18:49:57.250+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:49:57.250+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:49:58.541+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:50:09.778+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table FOSTER_FAM_AGNC
[2023-07-11T18:50:14.370+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table FOSTER_FAM_AGNC
[2023-07-11T18:50:29.077+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table FOSTER_FAM_AGNC
[2023-07-11T18:50:29.079+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.FOSTER_FAM_AGNC
[2023-07-11T18:50:29.179+0000] {SparkOracle2FileStore.py:91} INFO - processing 2 out of 26
[2023-07-11T18:50:29.179+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.EBT_EXPG_EXCPT
[2023-07-11T18:50:29.179+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:50:30.382+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.EBT_EXPG_EXCPT
[2023-07-11T18:50:30.382+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:50:31.534+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:50:32.156+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:50:32.156+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:50:34.691+0000] {SparkOracle2FileStore.py:114} INFO - 316506
[2023-07-11T18:50:34.692+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:50:35.990+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/EBT_EXPG_EXCPT
[2023-07-11T18:50:35.990+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:50:35.990+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:50:36.046+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:51:33.751+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table EBT_EXPG_EXCPT
[2023-07-11T18:52:36.661+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table EBT_EXPG_EXCPT
[2023-07-11T18:54:33.502+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table EBT_EXPG_EXCPT
[2023-07-11T18:54:33.503+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.EBT_EXPG_EXCPT
[2023-07-11T18:54:33.593+0000] {SparkOracle2FileStore.py:91} INFO - processing 3 out of 26
[2023-07-11T18:54:33.593+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.ENCL_ESTIMATE
[2023-07-11T18:54:33.593+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:34.762+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.ENCL_ESTIMATE
[2023-07-11T18:54:34.762+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:35.908+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:54:36.478+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:54:36.478+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:37.588+0000] {SparkOracle2FileStore.py:114} INFO - 25979
[2023-07-11T18:54:37.588+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:38.699+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/ENCL_ESTIMATE
[2023-07-11T18:54:38.699+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:54:38.699+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:54:38.767+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:54:41.820+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table ENCL_ESTIMATE
[2023-07-11T18:54:44.464+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table ENCL_ESTIMATE
[2023-07-11T18:54:52.991+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table ENCL_ESTIMATE
[2023-07-11T18:54:52.992+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.ENCL_ESTIMATE
[2023-07-11T18:54:53.076+0000] {SparkOracle2FileStore.py:91} INFO - processing 4 out of 26
[2023-07-11T18:54:53.076+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.UNIT
[2023-07-11T18:54:53.076+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:54.250+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.UNIT
[2023-07-11T18:54:54.250+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:54:55.529+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:54:56.165+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:54:56.165+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:57.350+0000] {SparkOracle2FileStore.py:114} INFO - 42879
[2023-07-11T18:54:57.350+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:54:58.591+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/UNIT
[2023-07-11T18:54:58.591+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:54:58.591+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:54:58.637+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:55:02.973+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table UNIT
[2023-07-11T18:55:13.537+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table UNIT
[2023-07-11T18:55:29.126+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table UNIT
[2023-07-11T18:55:29.127+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.UNIT
[2023-07-11T18:55:29.189+0000] {SparkOracle2FileStore.py:190} INFO - Tables Thresholds reached, restarting spark context
[2023-07-11T18:55:29.189+0000] {logging_mixin.py:149} INFO - Stopping Spark Context
[2023-07-11T18:55:29.260+0000] {logging_mixin.py:149} INFO - Restarting Spark Context
[2023-07-11T18:55:29.260+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-07-11T18:55:29.260+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-07-11T18:55:29.260+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-07-11T18:55:29.357+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-07-11T18:55:29.357+0000] {SparkOracle2FileStore.py:91} INFO - processing 5 out of 26
[2023-07-11T18:55:29.357+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.IEVS_SAVE_EXCEPT
[2023-07-11T18:55:29.357+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:28.675+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.IEVS_SAVE_EXCEPT
[2023-07-11T18:57:28.676+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T18:57:29.811+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T18:57:30.352+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T18:57:30.352+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:31.730+0000] {SparkOracle2FileStore.py:114} INFO - 397776
[2023-07-11T18:57:31.730+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T18:57:33.184+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/IEVS_SAVE_EXCEPT
[2023-07-11T18:57:33.184+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T18:57:33.184+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T18:57:33.700+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T18:58:27.052+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table IEVS_SAVE_EXCEPT
[2023-07-11T18:59:20.431+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table IEVS_SAVE_EXCEPT
[2023-07-11T19:01:11.075+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table IEVS_SAVE_EXCEPT
[2023-07-11T19:01:11.076+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.IEVS_SAVE_EXCEPT
[2023-07-11T19:01:11.154+0000] {SparkOracle2FileStore.py:91} INFO - processing 6 out of 26
[2023-07-11T19:01:11.154+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.RULES_ADMIN
[2023-07-11T19:01:11.154+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:12.336+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.RULES_ADMIN
[2023-07-11T19:01:12.336+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:13.390+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:01:13.961+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:01:13.961+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:15.125+0000] {SparkOracle2FileStore.py:114} INFO - 25885
[2023-07-11T19:01:15.126+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:16.349+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/RULES_ADMIN
[2023-07-11T19:01:16.349+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:01:16.349+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:01:16.399+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:01:18.499+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table RULES_ADMIN
[2023-07-11T19:01:20.750+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table RULES_ADMIN
[2023-07-11T19:01:28.464+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table RULES_ADMIN
[2023-07-11T19:01:28.465+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.RULES_ADMIN
[2023-07-11T19:01:28.534+0000] {SparkOracle2FileStore.py:91} INFO - processing 7 out of 26
[2023-07-11T19:01:28.534+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column ID on table PR_LRS.WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:01:28.534+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:30.002+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column ID on table PR_LRS.WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:01:30.003+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:01:32.009+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:01:33.118+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:01:33.118+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:35.019+0000] {SparkOracle2FileStore.py:114} INFO - 830945
[2023-07-11T19:01:35.019+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:01:36.430+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:01:36.430+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:01:36.430+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:01:36.483+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:03:07.332+0000] {SparkOracle2FileStore.py:154} INFO - no rows to upsert on table WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:04:43.031+0000] {SparkOracle2FileStore.py:158} INFO - Updating rows on table WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:08:51.497+0000] {SparkOracle2FileStore.py:172} INFO - no rows to delete on table WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:08:51.528+0000] {SparkOracle2FileStore.py:181} INFO - Table Processing complete for PR_LRS.WTW_24_MONTH_SIGN_DATE
[2023-07-11T19:08:51.668+0000] {SparkOracle2FileStore.py:91} INFO - processing 8 out of 26
[2023-07-11T19:08:51.668+0000] {logging_mixin.py:149} INFO - Attempting to get lowest value by column HST_ID on table PR_LRS.COUNTY_PARAMTR_ADMIN_HST
[2023-07-11T19:08:51.668+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:08:52.906+0000] {logging_mixin.py:149} INFO - Attempting to get max value by column HST_ID on table PR_LRS.COUNTY_PARAMTR_ADMIN_HST
[2023-07-11T19:08:52.906+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table by query...
[2023-07-11T19:08:53.992+0000] {logging_mixin.py:149} INFO - Attempting to read oracle table...
[2023-07-11T19:08:54.568+0000] {SparkOracle2FileStore.py:111} INFO - Filter Processor Disabled
[2023-07-11T19:08:54.568+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:08:55.674+0000] {SparkOracle2FileStore.py:114} INFO - 48818
[2023-07-11T19:08:55.674+0000] {logging_mixin.py:149} INFO - Attempting to read oracle rowcount by query...
[2023-07-11T19:08:57.092+0000] {logging_mixin.py:149} INFO - Checking if directory exists:/home/nicholas/dev/output/COUNTY_PARAMTR_ADMIN_HST
[2023-07-11T19:08:57.093+0000] {logging_mixin.py:149} INFO - Returning True
[2023-07-11T19:08:57.093+0000] {SparkOracle2FileStore.py:128} INFO - Should go in here if table dir exists
[2023-07-11T19:08:57.180+0000] {SparkOracle2FileStore.py:141} INFO - read dir table should not fail and go in here...
[2023-07-11T19:10:28.275+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 212, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 243, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 811, in refresh_from_db
    ti = qry.one_or_none()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:42.015+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:47.237+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-07-11T19:10:52.249+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
