[2023-06-02T16:50:05.509+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_virtualenv_example.creating_env manual__2023-06-02T16:50:04.891729+00:00 [queued]>
[2023-06-02T16:50:05.513+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_virtualenv_example.creating_env manual__2023-06-02T16:50:04.891729+00:00 [queued]>
[2023-06-02T16:50:05.514+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-02T16:50:05.520+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): creating_env> on 2023-06-02 16:50:04.891729+00:00
[2023-06-02T16:50:05.524+0000] {standard_task_runner.py:57} INFO - Started process 68 to run task
[2023-06-02T16:50:05.526+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_virtualenv_example', 'creating_env', 'manual__2023-06-02T16:50:04.891729+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/custom_dags/WrapperDag.py', '--cfg-path', '/tmp/tmpw4_jy7f_']
[2023-06-02T16:50:05.527+0000] {standard_task_runner.py:85} INFO - Job 187: Subtask creating_env
[2023-06-02T16:50:05.552+0000] {task_command.py:410} INFO - Running <TaskInstance: python_virtualenv_example.creating_env manual__2023-06-02T16:50:04.891729+00:00 [running]> on host 129355970c2d
[2023-06-02T16:50:05.592+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_virtualenv_example' AIRFLOW_CTX_TASK_ID='creating_env' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T16:50:04.891729+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-02T16:50:04.891729+00:00'
[2023-06-02T16:50:05.597+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Python-Delta-Lake/custom_dags/WrapperDag.py", line 59, in creating_env
    create_venv = PythonVirtualenvOperator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2023-06-02T16:50:05.600+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=python_virtualenv_example, task_id=creating_env, execution_date=20230602T165004, start_date=20230602T165005, end_date=20230602T165005
[2023-06-02T16:50:05.622+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 187 for task creating_env (missing keyword argument 'python_callable'; 68)
[2023-06-02T16:50:05.657+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-02T16:50:05.668+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
